import type { Routes } from './http/types.js';
import { authRoutes } from './domain/auth/routes.js';
import { platformRoutes } from './domain/platform/routes.js';
import { tenantAdminRoutes } from './domain/tenant-admin/routes.js';
import { propertyRoutes } from './domain/property/routes.js';
import { publicBookingRoutes } from './domain/bookings/public-routes.js';
import { adminBookingRoutes } from './domain/bookings/admin-routes.js';
import { paymentRoutes } from './domain/payments/routes.js';
import { guestAdminRoutes } from './domain/guests/admin-routes.js';
import { restaurantRoutes } from './domain/restaurant/routes.js';
import { requestRoutes } from './domain/requests/routes.js';
import { housekeepingRoutes } from './domain/housekeeping/routes.js';
import { maintenanceRoutes } from './domain/maintenance/routes.js';
import { experienceRoutes } from './domain/experiences/routes.js';
import { fileRoutes } from './domain/files/routes.js';
import { guideRoutes } from './domain/content/guide-routes.js';
import { portalRoutes } from './domain/portal/routes.js';
import { siteRoutes } from './domain/content/site-routes.js';
import { notificationRoutes } from './domain/notifications/routes.js';
import { reportRoutes } from './domain/reports/routes.js';
import { integrationRoutes } from './domain/integrations/routes.js';
import { eventRoutes } from './domain/events/routes.js';

export const registerRoutes: Routes = async (app, { config }) => {
  const opts = { config };
  await app.register(authRoutes, opts);
  await app.register(platformRoutes, opts);
  await app.register(tenantAdminRoutes, opts);
  await app.register(propertyRoutes, opts);
  await app.register(publicBookingRoutes, opts);
  await app.register(adminBookingRoutes, opts);
  await app.register(paymentRoutes, opts);
  await app.register(guestAdminRoutes, opts);
  await app.register(restaurantRoutes, opts);
  await app.register(requestRoutes, opts);
  await app.register(housekeepingRoutes, opts);
  await app.register(maintenanceRoutes, opts);
  await app.register(experienceRoutes, opts);
  await app.register(fileRoutes, opts);
  await app.register(guideRoutes, opts);
  await app.register(portalRoutes, opts);
  await app.register(siteRoutes, opts);
  await app.register(notificationRoutes, opts);
  await app.register(reportRoutes, opts);
  await app.register(integrationRoutes, opts);
  await app.register(eventRoutes, opts);
};
